name: metro_riders
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.5.3
  flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
     - family: Montserrat-V
       fonts:
         - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
