import 'package:get/route_manager.dart';

class Languages extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>{

    'en_US' :{
      'email_hint' : 'Email',
      'password_hint' : 'Password',
      'conform_password' : 'Conform Password',
      'reset_and_log_in' : 'Reset and Log In',
      'the_new_password_do_not_match' : 'The new password do not match',
      'login' : 'Log in',
      'reset_password' : 'Reset password',
      'forgot_password' : 'Forgot password?',
      'signup' : 'Sign up',
      'sign_in' : 'Sign In',
      'still_don’t_have_an_account' : 'Still don’t have an account?',
      'already_have_an_account' : 'Already have an account?',
      'by_clicking_“sign_up”' : 'By clicking “Sign up”, you agree to the Terms of Service',
      'restore_password' : 'Restore Password',
      'label_phone_number' : 'Phone Number',
      'congratulations' : 'Congratulations!',
      'you_successfully_signed_up_in-metro' : 'You successfully signed up in Metro!',
      'continue' : 'Continue',
      'conform' : 'Conform',
      'enter_your_email_address' : 'Enter your email address, we will send you an email with a link to reset your password',
      'an_email_with' : 'An email with a password reset link has been sent to your inbox',
      'a_confirmation_code_to_reset' : 'A confirmation code to reset password has been sent to your phone number',
      'create_a_new_password_for_your_account' : 'Create a new password for your account',
      'garage' : 'Garage',
      'store' : 'Store',
      'go' : 'GPo',
      'history' : 'History',
      'wallet' : 'Wallet',
      'my_garage' : 'My Garage',
      'scooters' : 'Scooters',
      'accessories' : 'Accessories',
      'bags_crossbody' : 'Bags Crossbody',
      'add_a_new_scooter' : 'Add a new scooter',
      'buy_now' : 'Buy now',
      'your_trips' : 'Your trips',
      'the_city' : 'The City',
      'search_for_places' : 'Search for places',
      'category' : 'Category',
      'close' : 'Close',
      'next' : 'Next',
      'your_contacts' : '1. Your contacts',
      'delivery' : '2. Delivery',
      'payment' : '3. Payment',
      'add_more' : '+ Add more',
      'contact_info' : 'Contact info',
      'phone_number' : 'Phone number',
      'buy' : 'Buy',
      'rent' : 'Rent',
      'country' : 'Country',
      'city' : 'City',
      'first_name' : 'First name',
      'last_name' : 'Last name',
      'address' : 'Address',
      'back' : 'Back',
      'delivery1' : 'Delivery',
      'payment1' : 'Payment',
      'card_number' : 'Card number',
      'expiration' : 'Expiration da...',
      'security_code' : 'Security code',
      'remember_me' : 'Remember me',
      'The City Pro' : 'the_city_pro',
      'add_a_new_card' : '+ Add a new card',
      'you_dont_have_any' : 'You don\'t have any added cards',
      'setting' : 'Setting',
      'profile' : 'Profile',
      'subscription' : 'Subscription',
      'Support' : 'Support',
      'driving_rules' : 'Driving rules',
      'privacy_policy' : 'Privacy policy',
      'about_us' : 'About us',
      'change_photo' : 'Change photo',
      'vino_costa' : 'Vino Costa',
      'your_email' : 'Your Email',


    }
  };


}